name: Basic Test

on:
  workflow_dispatch:
    inputs:
      os-variant:
        default: 'ubuntu-24.04'
        type: string
        description: 'Operating system'
      python-version:
        type: string
        description: 'Python interpreter version'
  workflow_call:
    inputs:
      os-variant:
        default: 'ubuntu-24.04'
        type: string
      python-version:
        type: string

jobs:
  base-tests:
    name: Basic Tests ${{ inputs.os-variant }} py${{ inputs.python-version }}
    runs-on: ${{ inputs.os-variant }}
    defaults:
      run:
        shell: bash -l {0}  # required for conda env
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4  # 10.1.0
        with:
          python-version: "${{ inputs.python-version }}"
      - name: Install Python packages
        run: uv sync

      - name: Install pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e  # 0.10.2
        with:
          pixi-version: 'v0.80.0'
          run-install: false
      - name: Install mamba
        uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39  # 3.2.1
        with:
          micromamba-version: '2.9.0-0'

      # setup-micromamba does not install a 'mamba' binary, only 'micromamba'
      - name: Set micromamba path
        run: echo "SCITACEAN_MAMBA_EXECUTABLE=$(which micromamba)" >> "$GITHUB_ENV"

      - name: Run Tests
        run: uv run pytest --env-tests
